post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphdmllciIsImlkIjoiNjJkOTEzMThmNzU5YTI0YWRiMzUzNWYyIiwiaWF0IjoxNjU4NDU3MjIwLCJleHAiOjE2NTg0NjA4MjB9.jehlH7IYfTerKiEMabzFwxJ7soyshA3cCBHYKCelCoQ

{
    "title": "the token getter has been refactored to middleware",
    "author": "javier",
    "url": "www.random.com",
    "likes": 0
}